# Base URL
baseurl:

# Site live URL
url: https://fmount.me

# Localhost 
#url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: "://fmount"
  comments: true
  # Little description about your site
  meta_description:
    Linux
    Virtualization
    fmount
    Networking
    Software Development
    Algorithms
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: fmount
    email: fmount9@autistici.org
    url: https://fmount.me

  # Google Analytics key, leave blank to ignore
  google_analytics_key: G-4M3PYE3F7C

  # Profile links, leave blank to ignore
  social: 
    github: fmount
    twitter: fmount9
    keybase: fmount
    rss: feed.xml
    talks: talks
# Conversion / Build settings 
  show_disclaimer: true

markdown:    kramdown
#markdown: redcarpet

# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge 

# Permalinks
permalink: pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

# Add support for the feed talks
plugins:
  - jekyll-feed
feed:
  path: feed.xml

## Add support for AsciiDoc posts using Asciidoctor
#gems:
#  - jekyll-asciidoc
#
#asciidoctor:
#    attributes:
#        - icons=font
#        - hardbreaks!
#        - source-highlighter=coderay
#Read time is based on the average reading speed of an adult 
#(roughly 275 WPM). We take the total word count of a post 
#and translate it into minutes. Then, we add 12 seconds for 
#each inline image. Boom, read time.
#
#(word_count/275) minutes + (12*images_number) seconds
